### ISSUE TITLE
CircleCI deploy fails

### ISSUE THREAD

**Issue by benswinburne** [motdotla/node-lambda#157]
When running on CircleCI I receive the following error. I have tried running it with node-lambda installed globally and as a devDependency. 

```
/opt/circleci/nodejs/v4.3.2/lib/node_modules/node-lambda/lib/main.js:264
        throw err;
        ^

Error: ENOENT: no such file or directory, mkdir '/tmp/@namespace/pkg-name-1475494922407'
```

Line 264 is `Lambda.prototype._cleanDirectory`

```
ubuntu@box389:~$ node -v
v4.3.2

ubuntu@box389:~$ npm -v
2.14.12

ubuntu@box389:~/pkg-name$ cat package.json | grep node-lambda
"node-lambda": "^0.8.10",
```

circle.yml
```
---
dependencies:
  post:
    - touch .env

machine:
  node:
    version: 4.3.2

deployment:
  production:
    branch: master
    commands:
      - node-lambda deploy -e production
```

The relevant environment variables are configured in the environment variables section of circle, rather than in a .env (hence the `touch .env`)
