### ISSUE TITLE
Travis integration?

### ISSUE THREAD

**Issue by ColinEberhardt** [motdotla/node-lambda#273]
Just a general question regarding automated deployment of Lambda functions via Travis. I can see a couple of options here:

The first would be to run the node-lambda CLI as an `after_success` step. For example:

package.json:

```
{
  "scripts": {
    "deploy": "node-lambda deploy"
  }
}
```

travis.yml:

```
after_success:
  - npm run deploy
```

However, travis also has [build in support for Lambda deployment](https://docs.travis-ci.com/user/deployment/lambda/):

e.g.

```
deploy:
  provider: lambda
  function_name: "lambda-test"
  region: "us-east-1"
  role: "arn:aws:iam::0123456789012:role/lambda_basic_execution"
  runtime: "nodejs4.3"
  handler_name: "handler"
  access_key_id: "AWS ACCESS KEY ID"
  secret_access_key: "AWS SECRET ACCESS KEY"
```

The only difference I can spot is that Travis doesn't seem to have any options for setting Lambda Environment variables.

Are there any other reasons why it might be better to use node-lambda from a Travis build?
